[platformio]
default_envs = tx

[env:tx]
platform = espressif32
board = esp32
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    arduino-lora/LoRa @ ^0.8.0
    adafruit/Adafruit SSD1306 @ ^2.5.9
    adafruit/Adafruit GFX Library @ ^1.11.9

[env:rx]
platform = espressif32
board = esp32
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    ; SX1280 Kütüphanesi
    arduino-lora/LoRa @ ^0.8.0

[env]
monitor_filters = esp32_exception_decoder
